spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/popularshop
    username: popularshop
    password: popularshop123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: false
